#ifndef _FH_EVENT_TYPES_H
#define _FH_EVENT_TYPES_H


enum fh_event_type {

	FH_EVT_UNKNOWN		= 0,

	/*
	 * WINDOW-EVENT
	 */

	FH_EVT_WINDOWCLOSE	= 1,
	
	FH_EVT_WINDOWENTER	= 2,
	FH_EVT_WINDOWLEAVE	= 3,

	FH_EVT_WINDOWSHOWN	= 4,
	FH_EVT_WINDOWHIDDEN	= 5,

	FH_EVT_WINDOWRESIZED	= 6,

	FH_EVT_ELEMENTADDED	= 7,

	/*
	 * ELEMENT-EVENT
	 */

	FH_EVT_ELEMENTREMOVED	= 8,
	FH_EVT_ELEMENTENTER	= 9,
	FH_EVT_ELEMENTLEAVE	= 10,
	FH_EVT_ELEMENTSELECT	= 11,
	FH_EVT_ELEMENTUNSELECT	= 12,

	/* MOUSE */
	FH_EVT_MOUSEMOTION	= 13,
	FH_EVT_MOUSEBUTTONDOWN	= 14,
	FH_EVT_MOUSEBUTTONUP	= 15,
	FH_EVT_MOUSEWHEEL	= 16,

	/* KEYBOARD */
	FH_EVT_KEYDOWN		= 17,
	FH_EVT_KEYUP		= 18

};


#endif /* _FH_EVENT_TYPES_H */
