#include "core/inc/predefined.h"


const u8 fh_ps_num = 3;
char *fh_ps_lst[3][3] = {
	{"flat", "res/predef/shaders/flat.vert", "res/predef/shaders/flat.frag"},
	{"ui", "res/predef/shaders/ui.vert", "res/predef/shaders/ui.frag"},
	{"model", "res/predef/shaders/model.vert", "res/predef/shaders/model.frag"}
};



char *fh_ps_batch_vshader = 
"#version 420 core\n"
"layout(location=0) in vec3 in_position;\n"
"layout(location=1) in int in_index;\n"
""
"uniform ivec2   u_frame;\n"
"uniform ivec4   u_rect[500];\n"
"uniform vec4    u_color[500];\n"
"uniform ivec4   u_radius[500];\n"
"uniform int     u_bwidth[500];\n"
"uniform vec4    u_bcolor[500];\n"
""
"flat out vec2   fs_frame;\n"
"out vec4        fs_color;\n"
"flat out vec4   fs_sides;\n"
"flat out vec2   fs_cpoints[4];\n"
"flat out ivec4  fs_radius;\n"
"flat out int    fs_bwidth;\n"
"flat out vec4   fs_bcolor;\n"
""
"void main() {\n"
"    vec2 lframe = u_frame * 0.5;\n"
"    ivec4 lrect = u_rect[in_index];\n"
"    ivec4 lradius = u_radius[in_index];\n"
""
"    fs_frame = ivec2(800, 600);\n"
"    fs_color = u_color[in_index];\n"
"    fs_sides = vec4(lrect.y, lrect.x+lrect.z, lrect.y+lrect.w, lrect.x);\n"
"    fs_cpoints = vec2[4](\n"
"        vec2(lrect.x + lradius[0], lrect.y + lradius[0]),\n"
"        vec2(lrect.x + lrect.z - lradius[1], lrect.y + lradius[1]),\n"
"        vec2(lrect.x + lrect.z - lradius[2], lrect.y + lrect.w - lradius[2]),\n"
"        vec2(lrect.x + lradius[3], lrect.y + lrect.w - lradius[3])\n"
"    );\n"
"    fs_radius = lradius;\n"
"    fs_bwidth = u_bwidth[in_index];\n"
"    fs_bcolor = vec4(0.0, 0, 0, 1.0);\n"
""
"    gl_Position = vec4((in_position.x - lframe.x) / lframe.x, (lframe.y - in_position.y) / lframe.y, in_position.z, 1);\n"
"}";

char *fh_ps_batch_fshader = 
"#version 420 core\n"
"\n"
"flat in vec2    fs_frame;\n"
"in vec4         fs_color;\n"
"flat in vec4    fs_sides;\n"
"flat in vec2    fs_cpoints[4];\n"
"flat in ivec4   fs_radius;\n"
"flat in int     fs_bwidth;\n"
"flat in vec4    fs_bcolor;\n"
"\n"
"out vec4 out_color;\n"
"\n"
"void main() {\n"
"    int corner = -1;\n"
"    vec2 loc = vec2(gl_FragCoord.x, fs_frame.y - gl_FragCoord.y);\n"
"    float alpha = 1.0;\n"
"    vec4 color;\n"
"    float dist;\n"
"    if(loc.y < fs_sides[0] || loc.y > fs_sides[2] || loc.x < fs_sides[3] || loc.x > fs_sides[1]) {\n"
"    	out_color = vec4(0, 0, 0, 0);\n"
"    }\n"
"    else {"
"    	if(loc.x <= fs_cpoints[0].x && loc.y <= fs_cpoints[0].y) corner = 0;\n"
"    	else if(loc.x >= fs_cpoints[1].x && loc.y <= fs_cpoints[1].y) corner = 1;\n"
"    	else if(loc.x >= fs_cpoints[2].x && loc.y >= fs_cpoints[2].y) corner = 2;\n"
"    	else if(loc.x <= fs_cpoints[3].x && loc.y >= fs_cpoints[3].y) corner = 3;\n"
"    	\n"
"    	if(corner < 0) {\n"
"    	    if(loc.y <= fs_sides[0] + fs_bwidth || loc.x >= fs_sides[1] - fs_bwidth || loc.y >= fs_sides[2] - fs_bwidth || loc.x <= fs_sides[3] + fs_bwidth) {\n"
"				color = fs_bcolor;\n"
"			}\n"
"    	    else {\n"
"				color = fs_color;\n"
"			}\n"
"    	}\n"
"    	else {\n"
"    	    dist = distance(loc, fs_cpoints[corner]);\n"
"    	    if(dist >= fs_radius[corner]) alpha = 0;\n"
"    	    else if(dist >= (fs_radius[corner] - fs_bwidth)) color = fs_bcolor;\n"
"    	    else color = fs_color;\n"
"    	}\n"
"    	\n"
"    	out_color = vec4(color.xyz, color.w * alpha);\n"
"	}"
"};";
