#ifndef _WUT_EVENT_TYPES_H
#define _WUT_EVENT_TYPES_H


enum wut_eEventType {

	WUT_EVT_UNKNOWN		= 0,

	/*
	 * WINDOW-EVENT
	 */

	WUT_EVT_WINDOWCLOSE	= 1,
	
	WUT_EVT_WINDOWENTER	= 2,
	WUT_EVT_WINDOWLEAVE	= 3,

	WUT_EVT_WINDOWSHOWN	= 4,
	WUT_EVT_WINDOWHIDDEN	= 5,

	WUT_EVT_WINDOWRESIZED	= 6,

	WUT_EVT_ELEMENTADDED	= 7,

	/*
	 * ELEMENT-EVENT
	 */

	WUT_EVT_ELEMENTREMOVED	= 8,
	WUT_EVT_ELEMENTENTER	= 9,
	WUT_EVT_ELEMENTLEAVE	= 10,
	WUT_EVT_ELEMENTSELECT	= 11,
	WUT_EVT_ELEMENTUNSELECT	= 12,

	/* MOUSE */
	WUT_EVT_MOUSEMOTION	= 13,
	WUT_EVT_MOUSEBUTTONDOWN	= 14,
	WUT_EVT_MOUSEBUTTONUP	= 15,
	WUT_EVT_MOUSEWHEEL	= 16,

	/* KEYBOARD */
	WUT_EVT_KEYDOWN		= 17,
	WUT_EVT_KEYUP		= 18

};


#endif /* _WUT_EVENT_TYPES_H */
